config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [ :options ]
    resources :events, only: [ :create ]
  end

  resources :registered_applications

  devise_for :users

  get 'about' => 'welcome#about'

  root to: 'welcome#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  has_many :registered_applications
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin']  = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  skip_before_action :verify_authenticity_token

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if registered_application.is_not nil
      @event = Event.new(event_params)

      if @event.valid?
        @event.save!
        render json: @event, status: :created
      else
        render json: {errors: @event.errors}, status: :unprocessable_entity
      end
    else
      render json: "Unregistered application", status: :unprocessable_entity
    end
  end

  def preflight
    head 200
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @registered_applications = RegisteredApplication.all
  end

  def new
    @registered_applications = RegisteredApplication.new
  end

  def create
    @registered_applications = RegisteredApplication.new(registered_applications_params)

    if @registered_applications.save
      redirect_to @registered_applications, notice: "Application was registered successfully."
    else
      flash[:error] = "Error registering application. Please try again."
      render :new
    end
  end

  def show
    @registered_applications = RegisteredApplication.find(params[:id])

    @events = @registered_applications.events.group_by(&:name)
  end

  def edit
    @registered_applications = RegisteredApplication.find(params[:id])
  end

  def update
    @registered_applications = RegisteredApplication.find(params[:id])
    @registered_applications.assign_attributes(registered_applications_params)

    if @registered_applications.save
      flash[:notice] = "Registered application was updated."
      redirect_to @registered_applications
    else
      flash[:error] = "Error saving registered application. Please try again."
      render :edit
    end
  end

  def destroy
    @registered_applications = RegisteredApplication.find(params[:id])

    if @registered_applications.destroy
      flash[:notice] = "\"#{@registered_applications.name}\" was deleted successfully."
      redirect_to action: :index
    else
      flash[:error] = "There was an error deleting the registered application."
      render :show
    end
  end
end

private

def registered_applications_params
  params.require(:registered_application).permit(:name, :url)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocmetrics", root_path %></li>
      <li><%= link_to "Registered Applications", registered_applications_path %></li>
      <li><%= link_to "About", about_path %></li>
      <div class="pull-right" style="margin-top:10px;">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |

          <%= link_to "Edit profile", edit_user_registration_path %> |
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path %> |
          <%= link_to "Sign In", new_user_session_path  %>
        <% end %>
      </div>
    </ul>

    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </div>

</body>
</html>

app/views/registered_applications/create.html.erb
<h1>RegisteredApplications#create</h1>
<p>Find me in app/views/registered_applications/create.html.erb</p>

app/views/registered_applications/destroy.html.erb
<h1>RegisteredApplications#destroy</h1>
<p>Find me in app/views/registered_applications/destroy.html.erb</p>

app/views/registered_applications/edit.html.erb
<h1>Edit Registered Application</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for registering applications:</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't begin with the letter "i".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @registered_applications do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
      </div>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, rows: 8, class: 'form-control', placeholder: "Enter application url" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/registered_applications/index.html.erb
<h1>Registered Applications</h1>

<div class="row">
  <div class="col-md-4">
    <%= link_to "Register New Application", new_registered_application_path, class: 'btn btn-success' %>
  </div>
  <br />
  <br />
  <br />
  <div class="col-md-8">
    <% @registered_applications.each do |reg_app| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to reg_app.name, reg_app %>
          </h4>
          <small>
            <% reg_app.url %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/registered_applications/new.html.erb
<h1>Register New Application</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for registering applications:</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't begin with the letter "i".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @registered_applications do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
      </div>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, rows: 8, class: 'form-control', placeholder: "Enter application url" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/registered_applications/show.html.erb
<h1><%= @registered_applications.name %></h1>

submitted <%= time_ago_in_words(@registered_applications.created_at) %> ago

<br />

<%= link_to "Edit Application", edit_registered_application_path, class: 'btn btn-success' %>
<%= link_to "Delete Application", @registered_applications, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this application?' } %>

<div class="row">
  <div class="col-md-8">
    <p class="lead">
      <br />
      Website: <a href="<%= @registered_applications.url %>"><%= @registered_applications.url %></a>
    </p>

    <p class="lead">
      <%= @registered_applications.events.count %> Event(s):
    </p>

    <% @registered_applications.events.each do |event| %>
      <%= event.name.capitalize %>
      <br>
    <% end %>

    <%= pie_chart @registered_applications.events.group(:name).count %>
  </div>
</div>

app/views/registered_applications/update.html.erb
<h1>RegisteredApplications#update</h1>
<p>Find me in app/views/registered_applications/update.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<h1>About Blocmetrics</h1>
<p>Created by: Alvin</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocmetrics</h1>
<p>This is the home page for Blocmetrics</p>